image: fedora:37
build:
  stage: build
  tags: 
    - k8s
  script:
    - yum -y install git hugo openssh-clients rsync wget
    - wget https://github.com/sass/dart-sass-embedded/releases/download/1.60.0/sass_embedded-1.60.0-linux-x64.tar.gz
    - tar -zxf sass_embedded-1.60.0-linux-x64.tar.gz
    - export PATH=$PWD/sass_embedded:$PATH
    - cd driconnect
    - git submodule init
    - git submodule update
    - hugo -t paige
    - ls -ltR
    - id
    - chmod go-rwx $driconnect_content
    - rsync -a --stats -e "ssh -oStrictHostkeyChecking=no -i $driconnect_content" public/ content@driconnect.sharcnet.ca:/var/www/html
 
