image: fedora:37
build:
  stage: build
  tags: 
    - k8s
  script:
    - yum -y install git hugo openssh-clients rsync
    - cd driconnect
    - git submodule init
    - git submodule update
    - hugo -t mini
    - ls -lR
    - chmod go-rwx $driconnect_content
    - rsync -a --stats -e "ssh -oStrictHostkeyChecking=no -i $driconnect_content" public/ content@driconnect.sharcnet.ca:/var/www/html
 
