image: klakegg/hugo:0.107.0-ext-alpine-ci
build:
  stage: build
  tags: 
    - k8s
  script:
    - apk add openssh-client rsync wget
#    - HUGO_VER=0.110.0
#    - wget https://github.com/gohugoio/hugo/releases/download/v$HUGO_VER/hugo_extended_${HUGO_VER}_linux-amd64.tar.gz
#    - tar -zvvxf hugo_extended_${HUGO_VER}_linux-amd64.tar.gz
    - DART_VER=1.60.0
    - wget https://github.com/sass/dart-sass-embedded/releases/download/$DART_VER/sass_embedded-${DART_VER}-linux-x64.tar.gz
    - tar -zvvxf sass_embedded-${DART_VER}-linux-x64.tar.gz
#    - chmod a+rx sass_embedded/dart-sass-embedded
    - export PATH=$PWD/sass_embedded:$PWD:$PATH
    - cd driconnect
    - which dart-sass-embedded
    - git submodule init
    - git submodule update
    - hugo -t paige
    - ls -ltR
    - chmod go-rx $driconnect_content
    - rsync -a --stats -e "ssh -oStrictHostkeyChecking=no -i $driconnect_content" public/ content@driconnect.sharcnet.ca:/var/www/html
