image: fedora:37
build:
  stage: build
  tags: 
    - k8s
  script:
    - yum -y install hugo openssh-clients rsync
    - (cd driconnect && hugo)
    - ls -lR
    - echo "nothing to see; move along..." > driconnect/public/index.html
    - chmod go-rwx $driconnect_content
    - rsync -a --stats -e "ssh -oStrictHostkeyChecking=no -i $driconnect_content" driconnect/public/ content@driconnect.sharcnet.ca:/var/www/html
    - date
 
