image: klakegg/hugo:0.100.2-ext-alpine-ci
build:
  stage: build
  tags: 
    - k8s
  script:
    - hugo -t paige
    - ls -ltR
    - chmod go-rwx $driconnect_content
    - rsync -a --stats -e "ssh -oStrictHostkeyChecking=no -i $driconnect_content" driconnect/public/ content@driconnect.sharcnet.ca:/var/www/html