image: fedora:37
build:
  stage: build
  tags: 
    - k8s
  script:
    - yum -y install hugo openssh-clients
    - (cd driconnect && hugo)
    - ls -lR
    - echo "nothing to see; move along..." > driconnect/public/index.html
    - chmod go-rwx $driconnect_content
    - ssh -oStrictHostkeyChecking=no -i $driconnect_content content@driconnect.sharcnet.ca hostname
    - date
 
