baseurl: "https://driconnectdemo.alliancecan.ca/"
copyright: "© 2025 Digital Research Alliance of Canada | Alliance de recherche numérique du Canada"
enablerobotstxt: false

markup:
  goldmark:
    renderer:
      unsafe: true
theme: "paige"
params:
  paige:
    color: "#856d2c"

defaultContentLanguage: "en"
languagecode: "en-us"
languages:
  en:
    languageName: "English"
    menu:
      main:
      - name: "Home"
        url: "/"
        weight: 1
      - name: "Program"
        url: "/program/"
        weight: 2
      - name: "Registration"
        url: "/registration/"
        weight: 3  
      #- name: "Attending"
        #url: "/attending/"
        #weight: 3
      #- name: "Accommodations"
        #url: "/accommodations/"
        #weight: 4
      - name: "Location"
        url: "/location/"
        weight: 4
      - name: "Code of Conduct"
        url: "/codeofconduct"
        weight: 5
    weight: 10
  fr:
    languageName: "Français"
    menu:
      main:
      - name: "Accueil"
        url: "/fr/"
        weight: 1
      - name: "Programme"
        url: "/fr/programme/"
        weight: 2
      - name: "Inscription"
        url: "/fr/inscription/"
        weight: 3  
      #- name: "Information"
        #url: "/fr/information/"
        #weight: 3
      #- name: "Hébergement"
        #url: "/fr/hebergement/"
        #weight: 4
      - name: "Lieu"
        url: "/fr/lieu/"
        weight: 4
      - name: "Code de conduite"
        url: "/fr/codedeconduite"
        weight: 5
    weight: 20