baseurl: "https://driconnectdemo.alliancecan.ca/"
copyright: "© 2023 Digital Research Alliance of Canada | Alliance de recherche numérique du Canada"
enablerobotstxt: false

markup:
  goldmark:
    renderer:
      unsafe: true
theme: "paige"
params:
  paige:
    color: "#856d2c"

defaultContentLanguage: "en"
languagecode: "en-us"
languages:
  en:
    languageName: "English"
    menu:
      main:
      - name: "Home"
        url: "/"
        weight: 1
      - name: "Program"
        url: "/program/"
        weight: 2
      - name: "Attend"
        url: "/attend/"
        weight: 3
      - name: "Conference Etiquette"
        url: "/etiquette/"
        weight: 4
      - name: "=> Français / Accueil"
        url: "/fr/"
        weight: 99
    weight: 10
  fr:
    languageName: "Français"
    menu:
      main:
      - name: "Accueil"
        url: "/fr/"
        weight: 1
      - name: "Programme"
        url: "/fr/programme/"
        weight: 2
      - name: "Y assister"
        url: "/fr/assister/"
        weight: 3
      - name: "Règles de bienséance"
        url: "/fr/etiquette/"
        weight: 4
      - name: "=> English / Home"
        url: "/"
        weight: 99
    weight: 20
